baseURL = 'thaiphong-blog.vercel.app/'
languageCode = 'vi'
title = 'Blog CÃ¡ NhÃ¢n '
theme = "PaperMod"

# Cáº¥u hÃ¬nh sitemap cho SEO (sau nÃ y cáº§n)
[sitemap]
  changefreq = "weekly"
  priority = 0.5

# Cáº¥u hÃ¬nh Param cá»§a Theme PaperMod
[params]
  defaultTheme = "auto" # Tá»± Ä‘á»™ng theo giao diá»‡n sÃ¡ng/tá»‘i cá»§a mÃ¡y
  # Hiá»ƒn thá»‹ nÃºt copy á»Ÿ cÃ¡c Ä‘oáº¡n code
  ShowCodeCopyButtons = true 
  # Hiá»ƒn thá»‹ má»¥c lá»¥c bÃ i viáº¿t
  ShowToc = true
  # Hiá»ƒn thá»‹ Ä‘Æ°á»ng dáº«n Ä‘iá»u hÆ°á»›ng (Breadcrumbs)
  ShowBreadCrumbs = true
  
 [params.profileMode]
  enabled = true
  title = "Há»“ ThÃ¡i Phong" 
  subtitle = """
  ğŸ‘‹ ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cÃ¡ nhÃ¢n cá»§a tÃ´i!
  
  """
  # Táº¡m thá»i dÃ¹ng link áº£nh online, lÃ¡t tÃ´i chá»‰ báº¡n thay áº£nh tháº­t
  imageUrl = "https://i.pinimg.com/736x/8b/16/7a/8b167af653c2399dd93b952a48740620.jpg" 
  imageTitle = "Avatar"
  imageWidth = 150
  imageHeight = 150

  # ThÃªm cÃ¡c nÃºt báº¥m Ä‘iá»u hÆ°á»›ng (Call to Action)
  [[params.profileMode.buttons]]
    name = "ğŸ“– Äá»c bÃ i viáº¿t"
    url = "/posts"

  [[params.profileMode.buttons]]
    name = "ğŸ“‚ Github cá»§a tÃ´i"
    url = "https://github.com/thaiphong89"

  [[params.profileMode.buttons]]
    name = "ğŸ“§ LiÃªn há»‡"
    url = "mailto:email@example.com"

# Pháº§n Social Icons giá»¯ nguyÃªn hoáº·c thÃªm má»›i
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/"
[[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/hothai.phong.1656/"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/"
  # --- Cáº¤U HÃŒNH MENU CHUáº¨N ---
[[menu.main]]
  identifier = "home"
  name = "HOME"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "ABOUT"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "resume"
  name = "RESUME"
  url = "/resume/"
  weight = 30

[[menu.main]]
  identifier = "gallery"
  name = "GALLERY"
  url = "/gallery/"
  weight = 40

[[menu.main]]
  identifier = "portfolio"
  name = "PORTFOLIO"
  url = "/portfolio/"
  weight = 50

[[menu.main]]
  identifier = "contact"
  name = "CONTACT"
  url = "/contact/"
  weight = 60
  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [outputs]
    home = ["HTML", "RSS", "JSON"] # Quan trá»ng: Pháº£i cÃ³ "JSON"
[[menu.main]]
    identifier = "search"
    name = "Search ğŸ”"  # Hoáº·c dÃ¹ng icon kÃ­nh lÃºp
    url = "/search/"
    weight = 100       # Sá»‘ lá»›n nháº¥t Ä‘á»ƒ nÃ³ náº±m ngoÃ i cÃ¹ng bÃªn pháº£i
    [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]